# Thread 2: Gender Injustice

### This thread looks at the crimes against women in the past decade and concludes important pointers from it. For ex- how the rate of crime against women is affected each year, whether criminals are convicted, etc.

## Cleaning

# 01. Import libraries

In [34]:
import pandas as pd
import sys
sys.path.append("..")

import utility as u

import importlib
importlib.reload(u)

# 02. Cleaning each file before using it for analysis

    NOTE

--> All the files will be loaded from `data/cleaned` (output from 01_EDA)

## a. file1.csv

In [35]:
# load the file
csv1= u.load_data("data/cleaned/file1.csv")

In [36]:
csv1.head(5)

                                          CRIME HEAD  year  cases
0                                               Rape  2001  16075
1          Kidnapping and Abduction of Women & Girls  2001  14645
2                                       Dowry Deaths  2001   6851
3  Assault on women with intent to outrage her mo...  2001  34124
4                     Insult to the modesty of Women  2001   9746

In [37]:
# checking the datatypes of all columns
u.eda(csv1)

=== DataFrame ===
Shape       : 242 rows × 3 cols
Duplicates  : 0

Column Summary:
             Dtype  Nulls  Null %  Uniques Flag
CRIME HEAD  object      0     0.0       11
year         int64      0     0.0       22
cases        int64      0     0.0      237

Numeric Stats:
          min       max      mean   median
year   2001.0    2022.0   2011.50   2011.5
cases     1.0  370616.0  45496.25  10277.5

Sample:
                                  CRIME HEAD  year  cases
0                                       Rape  2001  16075
1  Kidnapping and Abduction of Women & Girls  2001  14645
2                               Dowry Deaths  2001   6851

All datatypes are correct and need no changes. 

**file1 or csv1 is ready for 03_Analysis.**

## b. file2.csv

In [38]:
# load the file
csv2= u.load_data("data/cleaned/file2.csv")

In [39]:
csv2.head(5)

,Year,State_UT,State_UT_Raw,Row_Type,Crime_Head_Standardized,Crime_Head_Raw,Is_Detailed_Subcategory,Count
0,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Assault on Women with Intent to Outrage Modesty,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...,False,19.0
1,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Cruelty by Husband or Relatives,CRUELTY BY HUSBAND OR RELATIVES,False,9.0
2,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Dowry Deaths,DOWRY DEATH,False,0.0
3,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Immoral Traffic (Prevention) Act,IMMORAL TRAFFIC(PREVENTION)ACT,False,0.0
4,2001,Andaman & Nicobar Islands,A&N Islands,State/UT,Indecent Representation of Women (Prevention) Act,INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT,False,0.0

In [40]:
# checking the datatypes of all columns
u.eda(csv2)

=== DataFrame ===
Shape       : 5149 rows × 8 cols
Duplicates  : 0

Column Summary:
                           Dtype  Nulls  Null %  Uniques Flag
Year                       int64      0    0.00       14
State_UT                  object      0    0.00       36
State_UT_Raw              object      0    0.00       36
Row_Type                  object      0    0.00        1
Crime_Head_Standardized   object    900   17.48       14
Crime_Head_Raw            object      0    0.00       58
Is_Detailed_Subcategory     bool      0    0.00        2
Count                    float64      0    0.00     1410

Numeric Stats:
          min      max     mean  median
Year   2001.0   2014.0  2009.03  2010.0
Count     0.0  23278.0   580.16    26.0

Sample:
   Year                   State_UT State_UT_Raw  Row_Type                          Crime_Head_Standardized                                       Crime_Head_Raw  Is_Detailed_Subcategory  Count
0  2001  Andaman & Nicobar Islands  A&N Islands  State/UT  Assault on Women with Intent to Outrage Modesty  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY                    False   19.0
1  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                  Cruelty by Husband or Relatives                      CRUELTY BY HUSBAND OR RELATIVES                    False    9.0
2  2001  Andaman & Nicobar Islands  A&N Islands  State/UT                                     Dowry Deaths                                          DOWRY DEATH                    False    0.0

In [41]:
csv2['Crime_Head_Standardized'].unique()

array(['Assault on Women with Intent to Outrage Modesty',
       'Cruelty by Husband or Relatives', 'Dowry Deaths',
       'Immoral Traffic (Prevention) Act',
       'Indecent Representation of Women (Prevention) Act',
       'Insult to Modesty of Women', 'Kidnapping & Abduction of Women',
       'Rape', 'Commission of Sati (Prevention) Act',
       'Dowry Prohibition Act',
       'Importation of Girls from Foreign Country', nan,
       'Protection of Women from Domestic Violence Act',
       'Attempt to Commit Rape', 'Abetment of Suicide of Women'],
      dtype=object)

In [42]:
csv2['Crime_Head_Raw'].unique()

array(['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'CRUELTY BY HUSBAND OR RELATIVES', 'DOWRY DEATH',
       'IMMORAL TRAFFIC(PREVENTION)ACT',
       'INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT',
       'INSULT TO THE MODESTY OF WOMEN', 'KIDNAPPING & ABDUCTION', 'RAPE',
       'Assault on women with intent to outrage her Modest',
       'Commission of Sati (P) Act',
       'Cruelty by Husband or his relatives', 'Dowry Deaths',
       'Dowry Prohibition Act', 'Immoral Traffic (P) Act',
       'Importation of Girls from Foreign Country',
       'Indecent Representation of Women (P) Act',
       'Insult to the modesty of Women',
       'Kidnapping & Abduction of Women & Grils', 'Rape',
       '1 - Rape (Section 376 IPC)', '1.1 - Custodial Rape',
       '1.1.1 - Custodial_Gang Rape', '1.1.2 - Custodial_Other Rape',
       '1.2 - Rape other than Custodial', '1.2.1 - Rape_Gang Rape',
       '1.2.2 - Rape_Others', '10 - Dowry Prohibition Act, 1961',
       '11 - Indecent Representation of Women (Prohibition) Act, 1986',
       '12 - Commission of Sati Prevention Act 1987',
       '13 - Protection of Women from Domestic Violence Act, 2005',
       '14 - Immoral Traffic (Prevention) Act (Women Cases only)',
       '14.1 - Under ITP Section 5', '14.2 - Under ITP Section 6',
       '14.3 - Under ITP Section 7', '14.4 - Under ITP Section 8',
       '14.5 - Other Sections under ITP Act',
       '2 - Attempt to commit Rape (Section 376 & 511 IPC)',
       '3 - Kidnapping & Abduction of Women (Section 363,364,364A, 366-369 IPC)',
       '3.1 - Kidnaping & Abduction Section 363 IPC',
       '3.2 - Kidnaping & Abduction in order to Murder Section 364 IPC',
       '3.3 - Kidnapping for Ransom Section 364A',
       '3.4 - Kidnapping & Abduction of Women to compel her for marriage',
       '3.5 - Kidnapping & Abduction of Women-Other',
       '4 - Dowry Deaths (Section 304-B IPC)',
       '5 - Assault on Women with intent to outrage her Modesty_Total (Section 354 IPC)',
       '5.1 - Sexual Harassment',
       '5.2 - Assault on women with intent to Disrobe', '5.3 - Voyeurism',
       '5.4 - Stalking', '5.5 - Others',
       '6 - Insult to the Modesty of Women_Total (Section 509 IPC)',
       '6.1 - At Office premises', '6.2 - Other places related to work',
       '6.3 - In Public Transport system', '6.4 - in Other Places',
       '7 - Cruelty by Husband or his Relatives (Section 498A)',
       '8 - Importation of Girls from Foreign Country (Section 366B IPC)',
       '9 - Abetment of Suicides of Women u/s 306 IPC'], dtype=object)

In [43]:
# dropping totals from crime_head column
csv2= u.drop_totals(csv2, col= "Crime_Head_Standardized", keywords=[ "6 - Insult to the Modesty of Women_Total (Section 509 IPC)", "5 - Assault on Women with intent to outrage her Modesty_Total (Section 354 IPC)", "Total Crimes against Women", "TOTAL CRIME AGAINST WOMEN", "TOTAL CRIMES AGAINST WOMEN", "Total Crimes against Women"])
csv2= u.drop_totals(csv2, col= "Crime_Head_Raw", keywords=[ "6 - Insult to the Modesty of Women_Total (Section 509 IPC)", "5 - Assault on Women with intent to outrage her Modesty_Total (Section 354 IPC)", "Total Crimes against Women", "TOTAL CRIME AGAINST WOMEN", "TOTAL CRIMES AGAINST WOMEN", "Total Crimes against Women"])

Dropped 0 aggregate rows from 'Crime_Head_Standardized'
Dropped 72 aggregate rows from 'Crime_Head_Raw'

In [44]:
csv2['Crime_Head_Raw']

0       ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MO...
1                         CRUELTY BY HUSBAND OR RELATIVES
2                                             DOWRY DEATH
3                          IMMORAL TRAFFIC(PREVENTION)ACT
4         INDECENT REPRESENTATION OF WOMEN(PREVENTION)ACT
                              ...
5072                     6.3 - In Public Transport system
5073                                6.4 - in Other Places
5074    7 - Cruelty by Husband or his Relatives (Secti...
5075    8 - Importation of Girls from Foreign Country ...
5076        9 - Abetment of Suicides of Women u/s 306 IPC
Name: Crime_Head_Raw, Length: 5077, dtype: object

In [45]:
u.save_clean(csv2, "data/cleaned/file2.csv")

Saved | shape- (5077, 8)